### PR TITLE
Calendar height fix

### PR DESCRIPTION
**Pull request by x183**
Fixed the calendar height issue on larger screens.

### CODE REVIEW

**Review by Supergamer1337 — COMMENTED** [review]
Does this work even if the the screen size changes? Does the computation for the screen height actually rerun?

**Comment by x183** [comment]
> Does this work even if the the screen size changes? Does the computation for the screen height actually rerun?

Only runs on reload :sweat_smile:

**Comment by Supergamer1337** [comment]
Personally, I'd expect it to be responsive. Is this something you want to look into?

**Comment by x183** [comment]
I could try, but it won't look pretty

**Pull request merged**
