### PR TITLE
Fixed some dev-dependencies that broke by updating TypeScript

### PR DESCRIPTION
**Pull request by simon-wg**

### CODE REVIEW

**Review by GAsplund — COMMENTED** [review]
Will the two dev_setup scripts be used later, or why were they added?

**Comment by simon-wg** [comment]
They were changed to be executable, in the case of the frontend it's necessary to export an env-variable to allow unsafe ossl for an old version of something. The backend one was already there, and I just made it executable

**Review by ViktorYeet — APPROVED** [review]
👍

**Comment by simon-wg** [comment]
I don't know why it shows as empty though, I'll take a look at what's the matter with that, because they're supposed to have code

**Comment by simon-wg** [comment]
I'd guess it's a bug, they show as empty as no change was done in the file, only in the rwx-permissions

**Comment by GAsplund** [comment]
Yeah, that's what I reacted at. Lmk once you've figured it out and I'll approve

**Comment by simon-wg** [comment]
They **should** not be changed from the current ones at all, since it shows no lines removed or added. If you look at the files in the branch they are the same as the ones on main right now.

**Review by GAsplund — APPROVED** [review]
Should be fine then!

**Pull request merged**
