### PR TITLE
Quick visualization fix

### PR DESCRIPTION
**Pull request by Supergamer1337**
Fixes the issue where even rules allowed rules are visualized as disallowed.

### CODE REVIEW

**Comment by Supergamer1337** [comment]
How have I not learned to open the pr on the correct branch yet?

**Comment by Supergamer1337** [comment]
Eyy, det gick att ändra branch... Jag är bara blind.

**Comment by molleer** [comment]
You should add the filter to the end of line 15 instead. This will probably not work.

**Comment by Supergamer1337** [comment]
> You should add the filter to the end of line 15 instead. This will probably not work.

It worked fine when I tested it

**Comment by Supergamer1337** [comment]
I forgot about the fact that rules can overlap 😅 

Fixed now according to your solution.

**Pull request merged**
